# -*- coding: utf-8 -*-
"""CSE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1niZLmAuuSkWnzAO22M248NQbvkGxe5Fi
"""

# We Group of Computer Science Engineers are ready to help you.
# Mail Us Now at vatshayan007@gmail.com